version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: energy_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: energy_ingestion
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: energy_app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/energy_ingestion
      PORT: 3000
    depends_on:
      - db

volumes:
  postgres_data:
